[tool.poetry]
name = "past202005"
version = "0.1.0"
description = ""
authors = ["ryoheisato <thesugar87@gmail.com>"]

[tool.poetry.dependencies]
python = "3.8.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
